use One;
insert into geuf values('Rondônia','RO','A');
insert into geuf values('Acre','AC','A');
insert into geuf values('Amazonas','AM','A');
insert into geuf values('Roraima','RR','A');
insert into geuf values('Pará','PA','A');
insert into geuf values('Amapá','AP','A');
insert into geuf values('Tocantins','TO','A');
insert into geuf values('Maranhão','MA','A');
insert into geuf values('Piauí','PI','A');
insert into geuf values('Ceará','CE','A');
insert into geuf values('Rio Grande do Norte','RN','A');
insert into geuf values('Paraíba','PB','A');
insert into geuf values('Pernambuco','PE','A');
insert into geuf values('Alagoas','AL','A');
insert into geuf values('Sergipe','SE','A');
insert into geuf values('Bahia','BA','A');
insert into geuf values('Minas Gerais','MG','A');
insert into geuf values('Espírito Santo','ES','A');
insert into geuf values('Rio de Janeiro','RJ','A');
insert into geuf values('São Paulo','SP','A');
insert into geuf values('Paraná','PR','A');
insert into geuf values('Santa Catarina','SC','A');
insert into geuf values('Rio Grande do Sul','RS','A');
insert into geuf values('Mato Grosso do Sul','MS','A');
insert into geuf values('Mato Grosso','MT','A');
insert into geuf values('Goiás','GO','A');
insert into geuf values('Distrito Federal','DF','A');

select * from GEUF;
