use One;
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Abaetetuba',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Abel Figueiredo',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Acará',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Afuá',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Água Azul do Norte',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Alenquer',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Almeirim',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Altamira',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Anajás',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Ananindeua',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Anapu',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Augusto Corrêa',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Aurora do Pará',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Aveiro',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Bagre',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Baião',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Bannach',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Barcarena',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Belém',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Belterra',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Benevides',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Bom Jesus do Tocan',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Bonito',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Bragança',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Brasil Novo',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Brejo Grande do Araguaia',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Breu Branco',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Breves',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Bujaru',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Cachoeira do Arari',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Cachoeira do Piriá',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Cametá',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Canaã dos Carajás',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Capanema',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Capitão Poço',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Castanhal',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Chaves',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Colares',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Conceição do Araguaia',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Concórdia do Pará',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Cumaru do Norte',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Curionópolis',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Curralinho',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Curuá',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Curuçá',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Dom Eliseu',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Eldorado dos Carajás',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Faro',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Floresta do Araguaia',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Garrafão do Norte',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Goianésia do Pará',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Gurupá',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Igarapé-Açu',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Igarapé-Miri',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Inhangapi',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Ipixuna do Pará',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Irituia',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Itaituba',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Itupiranga',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Jacareacanga',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Jacundá',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Juruti',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Limoeiro do Ajuru',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Mãe do Rio',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Magalhães Barata',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Marabá',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Maracanã',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Marapanim',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Marituba',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Medicilândia',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Melgaço',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Mocajuba',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Moju',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Monte',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Muaná',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Nova Esperança do Piriá',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Nova Ipixuna',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Nova Timboteua',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Novo Progresso',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Novo Repartimento',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Óbidos',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Oeiras do Pará',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Oriximiná',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Ourém',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Ourilândia do Norte',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Pacajá',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Palestina do Pará',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Paragominas',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Parauapebas',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Pau D',5,'A'); 
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Peixe-Boi',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Piçarra',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Placas',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Ponta de Pedras',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Portel',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Porto de Moz',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Prainha',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Primavera',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Quatipuru',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Redenção',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Rio Maria',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Rondon do Pará',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Rurópolis',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Salinópolis',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Salvaterra',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Santa Bárbara do Pará',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Santa Cruz do Arari',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Santa Isabel do Pará',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Santa Luzia do Pará',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Santa Maria das Barreiras',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Santa Maria do Pará',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Santana do Araguaia',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Santarém',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Santarém Novo',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Santo Antônio do Tauá',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('São Caetano de Odivelas',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('São Domingos do Araguaia',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('São Domingos do Capim',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('São Félix do Xingu',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('São Francisco do Pará',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('São Geraldo do Araguaia',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('São João da Ponta',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('São João de Pirabas',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('São João do Araguaia',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('São Miguel do Guamá',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('São Sebastião da Boa',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Sapucaia',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Senador José Porfírio',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Soure',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Tailândia',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Terra Alta',5,'A'); 
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Terra Santa',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Tomé-Açu',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Tracuateua',5,'A'); 
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Trairão',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Tucumã',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Tucuruí',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Ulianópolis',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Uruará',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Vigia',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Viseu',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Vitória do Xingu',5,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Xinguara',5,'A');

select * from GECidade;
