insert into gecidade (Descricao, CodigoUF, flAtivo) values('Abaetetuba',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Abel Figueiredo',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Acará',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Afuá',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Água Azul do Norte',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Alenquer',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Almeirim',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Altamira',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Anajás',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Ananindeua',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Anapu',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Augusto Corrêa',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Aurora do Pará',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Aveiro',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Bagre',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Baião',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Bannach',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Barcarena',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Belém',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Belterra',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Benevides',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Bom Jesus do Tocan',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Bonito',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Bragança',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Brasil Novo',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Brejo Grande do Araguaia',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Breu Branco',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Breves',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Bujaru',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Cachoeira do Arari',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Cachoeira do Piriá',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Cametá',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Canaã dos Carajás',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Capanema',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Capitão Poço',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Castanhal',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Chaves',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Colares',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Conceição do Araguaia',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Concórdia do Pará',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Cumaru do Norte',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Curionópolis',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Curralinho',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Curuá',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Curuçá',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Dom Eliseu',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Eldorado dos Carajás',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Faro',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Floresta do Araguaia',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Garrafão do Norte',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Goianésia do Pará',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Gurupá',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Igarapé-Açu',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Igarapé-Miri',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Inhangapi',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Ipixuna do Pará',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Irituia',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Itaituba',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Itupiranga',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Jacareacanga',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Jacundá',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Juruti',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Limoeiro do Ajuru',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Mãe do Rio',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Magalhães Barata',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Marabá',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Maracanã',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Marapanim',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Marituba',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Medicilândia',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Melgaço',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Mocajuba',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Moju',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Monte',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Muaná',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Nova Esperança do Piriá',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Nova Ipixuna',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Nova Timboteua',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Novo Progresso',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Novo Repartimento',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Óbidos',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Oeiras do Pará',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Oriximiná',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Ourém',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Ourilândia do Norte',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Pacajá',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Palestina do Pará',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Paragominas',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Parauapebas',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Pau D',15,'A'); 
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Peixe-Boi',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Piçarra',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Placas',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Ponta de Pedras',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Portel',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Porto de Moz',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Prainha',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Primavera',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Quatipuru',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Redenção',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Rio Maria',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Rondon do Pará',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Rurópolis',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Salinópolis',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Salvaterra',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Santa Bárbara do Pará',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Santa Cruz do Arari',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Santa Isabel do Pará',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Santa Luzia do Pará',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Santa Maria das Barreiras',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Santa Maria do Pará',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Santana do Araguaia',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Santarém',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Santarém Novo',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Santo Antônio do Tauá',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('São Caetano de Odivelas',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('São Domingos do Araguaia',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('São Domingos do Capim',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('São Félix do Xingu',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('São Francisco do Pará',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('São Geraldo do Araguaia',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('São João da Ponta',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('São João de Pirabas',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('São João do Araguaia',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('São Miguel do Guamá',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('São Sebastião da Boa',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Sapucaia',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Senador José Porfírio',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Soure',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Tailândia',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Terra Alta',15,'A'); 
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Terra Santa',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Tomé-Açu',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Tracuateua',15,'A'); 
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Trairão',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Tucumã',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Tucuruí',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Ulianópolis',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Uruará',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Vigia',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Viseu',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Vitória do Xingu',15,'A');
insert into gecidade (Descricao, CodigoUF, flAtivo) values('Xinguara',15,'A');

select * from GECidade;
