CREATE TABLE Cidade
(
	idcidade             INTEGER identity(1,1) NOT NULL,
	cdibge				 integer not null,
	dscidade             varchar(60) NOT NULL ,
	flativo              CHAR(1) NOT NULL ,
	iduf                 INTEGER not null,
	constraint XPKCidade primary key(idcidade),
	constraint XFKUF foreign key(iduf) references UF(iduf)
);


insert into cidade(cdibge,dscidade,iduf,flativo) values('1500107','Abaetetuba',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1500131','Abel Figueiredo',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1500206','Acará',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1500305','Afuá',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1500347','Água Azul do Norte',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1500404','Alenquer',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1500503','Almeirim',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1500602','Altamira',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1500701','Anajás',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1500800','Ananindeua',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1500859','Anapu',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1500909','Augusto Corrêa',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1500958','Aurora do Pará',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1501006','Aveiro',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1501105','Bagre',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1501204','Baião',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1501253','Bannach',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1501303','Barcarena',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1501402','Belém',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1501451','Belterra',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1501501','Benevides',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1501576','Bom Jesus do Tocan',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1501600','Bonito',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1501709','Bragança',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1501725','Brasil Novo',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1501758','Brejo Grande do Araguaia',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1501782','Breu Branco',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1501808','Breves',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1501907','Bujaru',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1502004','Cachoeira do Arari',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1501956','Cachoeira do Piriá',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1502103','Cametá',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1502152','Canaã dos Carajás',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1502202','Capanema',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1502301','Capitão Poço',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1502400','Castanhal',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1502509','Chaves',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1502608','Colares',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1502707','Conceição do Araguaia',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1502756','Concórdia do Pará',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1502764','Cumaru do Norte',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1502772','Curionópolis',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1502806','Curralinho',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1502855','Curuá',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1502905','Curuçá',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1502939','Dom Eliseu',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1502954','Eldorado dos Carajás',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1503002','Faro',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1503044','Floresta do Araguaia',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1503077','Garrafão do Norte',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1503093','Goianésia do Pará',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1503101','Gurupá',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1503200','Igarapé-Açu',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1503309','Igarapé-Miri',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1503408','Inhangapi',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1503457','Ipixuna do Pará',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1503507','Irituia',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1503606','Itaituba',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1503705','Itupiranga',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1503754','Jacareacanga',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1503804','Jacundá',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1503903','Juruti',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1504000','Limoeiro do Ajuru',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1504059','Mãe do Rio',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1504109','Magalhães Barata',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1504208','Marabá',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1504307','Maracanã',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1504406','Marapanim',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1504422','Marituba',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1504455','Medicilândia',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1504505','Melgaço',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1504604','Mocajuba',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1504703','Moju',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1504802','Monte',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1504901','Muaná',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1504950','Nova Esperança do Piriá',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1504976','Nova Ipixuna',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1505007','Nova Timboteua',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1505031','Novo Progresso',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1505064','Novo Repartimento',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1505106','Óbidos',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1505205','Oeiras do Pará',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1505304','Oriximiná',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1505403','Ourém',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1505437','Ourilândia do Norte',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1505486','Pacajá',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1505494','Palestina do Pará',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1505502','Paragominas',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1505536','Parauapebas',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1505551','Pau D',15,'A'); 
insert into cidade(cdibge,dscidade,iduf,flativo) values('1505601','Peixe-Boi',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1505635','Piçarra',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1505650','Placas',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1505700','Ponta de Pedras',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1505809','Portel',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1505908','Porto de Moz',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1506005','Prainha',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1506104','Primavera',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1506112','Quatipuru',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1506138','Redenção',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1506161','Rio Maria',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1506187','Rondon do Pará',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1506195','Rurópolis',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1506203','Salinópolis',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1506302','Salvaterra',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1506351','Santa Bárbara do Pará',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1506401','Santa Cruz do Arari',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1506500','Santa Isabel do Pará',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1506559','Santa Luzia do Pará',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1506583','Santa Maria das Barreiras',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1506609','Santa Maria do Pará',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1506708','Santana do Araguaia',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1506807','Santarém',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1506906','Santarém Novo',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1507003','Santo Antônio do Tauá',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1507102','São Caetano de Odivelas',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1507151','São Domingos do Araguaia',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1507201','São Domingos do Capim',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1507300','São Félix do Xingu',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1507409','São Francisco do Pará',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1507458','São Geraldo do Araguaia',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1507466','São João da Ponta',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1507474','São João de Pirabas',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1507508','São João do Araguaia',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1507607','São Miguel do Guamá',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1507706','São Sebastião da Boa',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1507755','Sapucaia',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1507805','Senador José Porfírio',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1507904','Soure',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1507953','Tailândia',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1507961','Terra Alta',15,'A'); 
insert into cidade(cdibge,dscidade,iduf,flativo) values('1507979','Terra Santa',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1508001','Tomé-Açu',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1508035','Tracuateua',15,'A'); 
insert into cidade(cdibge,dscidade,iduf,flativo) values('1508050','Trairão',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1508084','Tucumã',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1508100','Tucuruí',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1508126','Ulianópolis',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1508159','Uruará',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1508209','Vigia',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1508308','Viseu',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1508357','Vitória do Xingu',15,'A');
insert into cidade(cdibge,dscidade,iduf,flativo) values('1508407','Xinguara',15,'A');